name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug --stacktrace --no-daemon -x test
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: TeamCode/build/outputs/apk/debug/TeamCode-debug.apk 
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: actions/download-artifact@v3
        name: Create local changes
        with:
          name: apk
          path: HelpPage/apk/bin
    
      - name: Display structure of downloaded files
        run: ls -laR HelpPage/apk/bin
        
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
