name: Java Build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up the JDK environment
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        cache: gradle

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
