name: Fetch local upstream
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update testing branches from master
        run: |
          # Configure Git user info
          # git config user.name "GitHub Actions Bot"
          # git config user.email "actions@github.com"
          # Get all branches
          rm -rf wksp
          mkdir -p wksp
          cd wksp
          touch b.txt
          echo $(curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/octocat/hello-world/branches \
            -o b.txt \ 
            | jq '[.[] | .name]') \
            >> b.txt
          cat b.txt
